name: qyadati-apisix-local-server
version: 1.0.0
routes:
- name: local-server-health-check
  uri: /health
  methods:
  - GET
  plugins:
    response-rewrite:
      body: '{"status":"healthy","service":"qyadati-gateway","env":"local-server","flavor":"on-premise"}'
      headers:
        set:
          Content-Type: application/json
- name: local-server-api-docs
  uri: /docs*
  methods:
  - GET
  upstream:
    name: local-server-docs-upstream
    type: roundrobin
    nodes:
    - host: 192.168.1.50
      port: 3000
      weight: 1
- name: local-server-auth-service
  uri: /api/v1/auth/*
  methods:
  - GET
  - POST
  - PUT
  - DELETE
  - OPTIONS
  plugins:
    cors:
      allow_origins: '*'
      allow_methods: '*'
      allow_headers: '*'
  upstream:
    name: local-server-auth-upstream
    type: roundrobin
    nodes:
    - host: 192.168.1.50
      port: 4000
      weight: 1
- name: local-server-users-service
  uri: /api/v1/users/*
  methods:
  - GET
  - POST
  - PUT
  - DELETE
  - OPTIONS
  plugins:
    cors:
      allow_origins: '*'
      allow_methods: '*'
      allow_headers: '*'
  upstream:
    name: local-server-users-upstream
    type: roundrobin
    nodes:
    - host: 192.168.1.50
      port: 4001
      weight: 1
- name: local-server-payments-service
  uri: /api/v1/payments/*
  methods:
  - GET
  - POST
  - PUT
  - DELETE
  - OPTIONS
  plugins:
    cors:
      allow_origins: '*'
      allow_methods: '*'
      allow_headers: '*'
  upstream:
    name: local-server-payments-upstream
    type: roundrobin
    nodes:
    - host: 192.168.1.50
      port: 4002
      weight: 1
- name: local-server-courses-service
  uri: /api/v1/courses/*
  methods:
  - GET
  - POST
  - PUT
  - DELETE
  - OPTIONS
  plugins:
    cors:
      allow_origins: '*'
      allow_methods: '*'
      allow_headers: '*'
  upstream:
    name: local-server-courses-upstream
    type: roundrobin
    nodes:
    - host: 192.168.1.50
      port: 4003
      weight: 1
services: []
upstreams:
- id: لابيلابلاب
  name: لابيلابلابلالا
  type: roundrobin
  nodes:
    host.docker.internal:3001: 1
global_rules: []
